import type { Metadata } from "next";
import { Baskervville, Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Image from "next/legacy/image";
import Ellipse from "/public/marqueseleao/ellipse4.webp";

const baskervville = Baskervville({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-baskervville",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Imobiliária Marques & Leão",
  description: "Generated by create next app",
};

async function getData() {
  const empresa_id: any =
    process.env.EMPRESA_ID ?? process.env.NEXT_PUBLIC_EMPRESA_ID;
  const uri =
    process.env.BACKEND_API_URI ??
    (process.env.NEXT_PUBLIC_BACKEND_API_URI as string);

  const data = await fetch(
    `${uri}/empresas/site/${empresa_id}`,
    {
      next: { tags: ["empresas"], revalidate: 3600 },
    }
  );

  if (!data.ok) {
    throw new Error("Failed to fetch data");
  }

  return {
    empresa: await data.json(),
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { empresa } = await getData();

  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${baskervville.variable} font-montserrat antialiased overflow-x-hidden`}
      >
        <div className="absolute right-0 top-0 w-1/2 lg:w-[40%] aspect-square overflow-hidden">
          <Image
            draggable={false}
            className="absolute top-[-20%] lg:top-[-35%] opacity-50 right-[-35%] lg:right-[-30%] w-full"
            src={Ellipse}
            alt="Ellipse blur"
          />
        </div>
        {children}
        <Footer empresa={empresa} />
      </body>
    </html>
  );
}
